### ISSUE TITLE
Improve speed by reducing conditions when indicator is ready

### ISSUE THREAD

**Issue by femtotrader** [nardew/talipp#100]
Hello,

I wonder if this code couldn't be improved to speedup process
Compare for example
https://github.com/nardew/talipp/blob/77782fb464c8cef62047da8de477147b84ed1c39/talipp/indicators/TEMA.py
with
https://github.com/femtotrader/IncTA.jl/blob/main/src/indicators/TEMA.jl (sorry Julia code not Python)

I consider that I should reach a minimum of if statements when the indicator is "ready".

I haven't benchmark it, but I'm pretty sure that is more efficient.

What is you opinion about that?

Kind regards

**Comment by nardew** [comment]
I do not see a difference in the performance, not even in theory. My code performs 3 ifs in the positive case, yours as well. Besides that, overhead of operations like that is marginal. If microseconds matter, python is probably not the best language to begin with.

**Comment by nardew** [comment]
Okay, I think I got what you are suggesting. Basically when all subindicators have data, do not perform individual ifs anymore. While you are right, as I mentioned above, the difference will be miniscule.
