### ISSUE TITLE
RSI indicator:  I seem to be getting too high a value

### ISSUE THREAD

**Issue by hoagluk** [nardew/talipp#102]
Hi.  For the stock Intel (INTC), in my Python program, using the talipp library, I'm getting an RSI value for today (12/27/2023) of 83.  My other two services, Stockcharts.com and Yahoo Finance give it an RSI of 76.  Am I doing something wrong?  I think I'm running talipp version 1.9.1:

![image](https://github.com/nardew/talipp/assets/7740655/4a964a7a-9a7b-486f-84c4-676bd12c16e7)

First, my baseline, Stockcharts.com:

![image](https://github.com/nardew/talipp/assets/7740655/9108ecef-0d98-4dff-8326-1e27e17a23c9)

Then my program:

![image](https://github.com/nardew/talipp/assets/7740655/35941a67-da5e-417c-b850-76cd8c2dfcc4)

And output:

![image](https://github.com/nardew/talipp/assets/7740655/b91bce67-0a7a-4d2d-a27b-187b7c91fac5)

Thanks so much.  I LOVE the library!

**Comment by nardew** [comment]
Hi, if I understand it right, you are providing only 28 values into the RSI indicator. That's very few. Supply at least 100 values because RSI takes older values into account (indirectly).

**Comment by hoagluk** [comment]
Ok, thanks. Ill

Karl Hoaglund
213/986-6946 (cell/text)
________________________________

**Comment by hoagluk** [comment]
Sorry, I fat-fingered the send button. I'll give that a try and write you back.

Karl Hoaglund
213/986-6946 (cell/text)
________________________________

**Comment by hoagluk** [comment]
Hi! As you suggested, I tried it with 100 historical values.  That brought the number down a little, but it's still too high.  (This would have signaled me out of my position about three days too early.)  Here are the first and last values of my test:

![image](https://github.com/nardew/talipp/assets/7740655/8864cbdf-7630-4da5-a6a3-df1c99fbc17f)

![image](https://github.com/nardew/talipp/assets/7740655/0c3d00dd-61e5-4db7-86bc-a45bccc3df4d)

Thanks for your help!

**Comment by nardew** [comment]
If I run on INTC numbers over last year I am getting number `76.24498025235394` which seems correct.

**Comment by hoagluk** [comment]
Ah yes.  That's exactly the right number.

Thank you!  I'm very happy to have the solution and will happily implement it.  It is a surprise, though, that so much data has to be front-loaded in order to get that indicator to work right.  I don't think I've seen that with other indicators, or stated in the documentation anywhere.  But thanks again for your help and for the library.

**Comment by hoagluk** [comment]
Ah.  I also found there was an error in my program.  The part indicated is incorrect:

![image](https://github.com/nardew/talipp/assets/7740655/207751dd-3c83-4707-b3e0-80f90e31dcc6)

It should have been "rsi[-1]".  I think that is the correct way to get the latest calculated value.

I still had to front-load about 150 values to get the calculation to be correct.

**Comment by nardew** [comment]
Yes, indicators are accessed as standard lists. 

It is not surprising at all that you may need that many values to get the same number as in the chart you pasted. Some indicators use their previous values to calculate new ones which means all input values are used in every calculation in a way. It’s not that one number was correct and the other wrong. Both were correct, just calculated on different data.
