### ISSUE TITLE
Inconsitent naming mult or multiplier

### ISSUE THREAD

**Issue by femtotrader** [nardew/talipp#106]
https://github.com/nardew/talipp/blob/77782fb464c8cef62047da8de477147b84ed1c39/talipp/indicators/TTM.py#L33

https://github.com/nardew/talipp/blob/0ec35c850c91530f1256fc1f8fe851a02e19c63f/talipp/indicators/BB.py#L28

I noticed that because I'm using keywords arguments for indicators in my implementation

(feel free to close if you don't want to fix that)

**Comment by nardew** [comment]
Thanks, fixed in https://github.com/nardew/talipp/pull/96.
