### ISSUE TITLE
Can we initialize an indicator with already calculated values and start calculating afterwards ? 

### ISSUE THREAD

**Issue by varunsingla211** [nardew/talipp#115]
If i have calculated the values of lets say n-1 days already and stored somewhere. 
I would like to initiate the indicator with stored values of n-1 days and start calculating from today onwards.

Is it possible to do so ?

**Comment by nardew** [comment]
Hi @varunsingla211 , no, this is not possible. The library maintains internal structures for each indicator which couldn't be populated without original input values.

**Comment by varunsingla211** [comment]
Ok thanks. Also this is off the context but i am looking for a feature which could convert real time tick data into candles of different time intervals.

Suppose i am receiving tick data from a webhook and keep passing that data to a function which will give me an ohlc value after every 1 minute or whatever time i choose... 

Do you think this kind if functionality would be a good thing for your library, since this library is more focused on real time processing
