### ISSUE TITLE
ALMA - discrepancy between talipp and tradingview

### ISSUE THREAD

**Issue by filipemarques87** [nardew/talipp#128]
First of all, congratulation for this library, it is really cool for realtime processing.

I was checking the ALMA indicator and I noticed some discrepancy between this library and tradingview.

I did some tests and update the code to this, the results are now the same
```
s = self.period / self.sigma # s = self.period / float(self.sigma) -> no need the float cast
m = (self.period - 1) * self.offset # m = int((self.period - 1) * self.offset) -> the int cast is truncating the decimal part
```

**Comment by nardew** [comment]
Hi, thanks for the proposal.

Ad `s`, the float cast is needed if `sigma` is an integer.
Ad `m`, I found it like this somewhere but not sure where. Even trading view says `//m = math.floor(offset * (windowsize - 1)) // Used as m when math.floor=true` though I am not 100% sure what they mean (how does one set math.floor to true?)

If I remove flooring for `m`, indeed I get the same results as in trading view. I will do this change. Thanks.

**Comment by nardew** [comment]
Delivered in `2.2.1`.
