### ISSUE TITLE
 rsi().add() and tsi().add() issue when global variables

### ISSUE THREAD

**Issue by hysech** [nardew/talipp#131]
Hello Nardew,
sorry to disturb you. I used your older version of talipp at the same code without any issue. After the upgrade to 2.2.1 I can only initialize indicators RSI and TSI but cannot add a new input using rsi().add() and tsi().add().
Maybe the reason is in my using global variables gl.rsi, gl. tsi or other trik in Python, but I am stalling 2 weeks already. To go on in debugging I have to initialize rsi, tsi repeatedly and after a limit use 
.purge_oldest which for some reason is working!?!? Of course repeating the initializations is very time consuming and downgrading to older version is the last step?
I tried to add type(R/TSI) to the declaration of the global var. but it did not help.
Thank you very much in advance for your time and help.
With my regards,
                                Hynek Sechovsky 

[talipp_issue.pdf](https://github.com/nardew/talipp/files/15138340/talipp_issue.pdf)

**Comment by nardew** [comment]
Duplicate of #134

**Comment by hysech** [comment]
Hi Nardew,
I had a few days break with limited access to inet. Nice to hear from you.
I will prepare better document tomorrow with the error messages and dump,
Hynek

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Neobsahuje
žádné viry.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

čt 2. 5. 2024 v 8:38 odesílatel nardew ***@***.***> napsal:
