### ISSUE TITLE
KDJ Indicator request

### ISSUE THREAD

**Issue by NeoWang9999** [nardew/talipp#132]
https://docs.anychart.com/Stock_Charts/Technical_Indicators/KDJ#:~:text=KDJ%20indicator%20is%20otherwise%20known,line%20called%20the%20J%20line.

**Comment by nardew** [comment]
Hi, `KDJ` is just regular `Stoch` with additional `J` value which is calculated as `3 × the day K value - 2 × the day D value`. Since this `J` can be calculated manually easily, I do not see a benefit of including the indicator in the library. If you feel otherwise, reopen and let me know.
