### ISSUE TITLE
FibRetracement Documentation missing

### ISSUE THREAD

**Issue by nkjadhav** [nardew/talipp#133]
No content available at FibRetracement section.
URL - https://nardew.github.io/talipp/latest/reference/talipp/indicators/FibRetracement/

**Comment by nardew** [comment]
Hi, you are right, I will add some description. `FibRetracement` is just a class with constants, was your point just to add doc or are you looking for something specific?

**Comment by nkjadhav** [comment]
Yes, please add some description in doc. It will be of great help.

**Comment by nardew** [comment]
The documentation has been updated.
