### ISSUE TITLE
Zigzag Indicator request

### ISSUE THREAD

**Issue by P-Lamont** [nardew/talipp#135]
https://stackoverflow.com/questions/62454181/zigzag-indicator-in-python
 Can you add something like this?

**Comment by nardew** [comment]
Hi, talipp already provides [Pivot High Low](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html#attach-bucket-policy) which provides similar functionality to zig zag. Read more e.g. [here](https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/pivot-points-high-low).

**Comment by P-Lamont** [comment]
Thanks @nardew for replying. I have looked into it already. The reason I have suggested is because Pivot Points uses time to determine the pivot points while zigzag uses percentage.

**Comment by nardew** [comment]
@P-Lamont delivered in `2.3.0`.
