### ISSUE TITLE
Implement VWAP

### ISSUE THREAD

**Issue by pramitbiswas** [nardew/talipp#47]
with pandas: `round(np.cumsum(x['volume']*(x['high']+x['low']+x['close'])/3) / np.cumsum(x['volume']),2)`
Here, I think it will be better to store data (`np.cumsum(x['volume']*(x['high']+x['low']+x['close'])/3)` and `np.cumsum(x['volume'])`) at each step to reduce the calculation at each step.

**Comment by pramitbiswas** [comment]
#48 added.

**Comment by pramitbiswas** [comment]
#49 added for test.

**Comment by pramitbiswas** [comment]
#50 added for VWAP indicator.

**Comment by nardew** [comment]
Merged with #50, published in `1.6.0`.
