### ISSUE TITLE
feature request,add  "time" column

### ISSUE THREAD

**Issue by guzuomuse** [nardew/talipp#56]
add "time" colume to OHLCV so we can get the current datetime of the data. 

OHLCV to TOHLCV? 

or allow input_values to be pandas DataFrame?

**Comment by nardew** [comment]
Hi @guzuomuse , are you after something like #57? If yes, let me know and I will merge it.

**Comment by guzuomuse** [comment]
@nardew .sorry for late reply. yes. that's exactly what i need. thanks

**Comment by nardew** [comment]
Delivered in `1.7.0`.
