### ISSUE TITLE
TTM Squeeze Indicator

### ISSUE THREAD

**Issue by pattertj** [nardew/talipp#64]
Hey, first off, love your repo!

Second, I'd like to see TTM Squeeze added. I think this should be doable as it is a mix of indicators you already have:

- Donchian 
- SMA
- Bollinger Bands
- Keltner channels

https://school.stockcharts.com/doku.php?id=technical_indicators:ttm_squeeze

I might be able to code this myself and contribute, but am wondering how to handle outputting both the histogram value and squeeze indicator. It has two parts.

Let me know and I'll see what I can do!

**Comment by nardew** [comment]
Hi @pattertj , thanks for the interest. The indicator should be easy to implement given most subindicators it uses are already part of talipp. The only missing part is the calculation of linear regression which is not trivial. I am not saying it is difficult but this part will take some time. I will look more into and let you know the estimate when it could be included.

**Comment by nardew** [comment]
@pattertj I push the new indicator at `ttm` branch. Do you fancy trying it? If not, I will merge and publish it directly.

**Comment by pattertj** [comment]
Awesome! I can wire it into my trader today and let you know in the next day or so, if that works?

**Comment by pattertj** [comment]
@nardew - everything looks good to me! Thanks for adding this so quickly!
