### ISSUE TITLE
compare performance / accuracy with ta-lib-rt?

### ISSUE THREAD

**Issue by mw66** [nardew/talipp#71]
Hi,

There is another incremental version of ta-lib:

https://github.com/trufanov-nok/ta-lib-rt

if you have time, can you compare the performance / accuracy with ta-lib-rt?

Thanks

**Comment by nardew** [comment]
Hi @mw66,
I am aware of the package but I have never done side by side comparison and it is not a priority for me at the moment. If by any chance you get to testing it yourself, please do let me know the outcomes.

Andrej
