### ISSUE TITLE
Drop support for Python `3.6`, `3.7`, add for `3.10`, `3.11`

### ISSUE THREAD

**Issue by xzmeng** [nardew/talipp#75]
Python `3.6`, `3.7` have reached their end-of-life of their release cycles.
[Current tests workflow will fail](https://github.com/xzmeng/talipp/actions/runs/6263139042/job/17006855299) because `actions/setup-python` [does not  provide `3.6` on `ubuntu-latest`](https://github.com/actions/setup-python/issues/544#issuecomment-1332535877):
So I propose to update the Python versions and happy to make a PR if you think it reasonable.

**Comment by nardew** [comment]
Hi @xzmeng , thanks for pointing this out. If you can open a PR with all the changes, that would be great. Thanks!
