### ISSUE TITLE
Why aren't the lengths of the data results aligned?

### ISSUE THREAD

**Issue by Gwill** [nardew/talipp#77]
Like This:

```
sma = SMA(3)
print(f'{sma}')  # output: []

sma.add_input_value(1)
print(f'{sma}')  # output: [None]

sma.add_input_value(2)
print(f'{sma}')  # output: [None, None]

sma.add_input_value(3)
print(f'{sma}')  # output: [None, None, 2.0]
```

**Comment by nardew** [comment]
Data are aligned with input vector from right. That's how the library works at the moment. The reasons are purely technical, mainly to support properly all incremental operations.

**Comment by nardew** [comment]
@Gwill this feature is now implemented in PR https://github.com/nardew/talipp/pull/96. It is not released yet but you can clone and checkout the branch and give it a try.
