### ISSUE TITLE
STC-indicator

### ISSUE THREAD

**Issue by PieceOfGood** [nardew/talipp#81]
Could you also add the [Schaff Trend Cycle(STC)](https://www.tradingview.com/script/UkWZRgLG-Schaff-Trend-Cycle/) indicator?
It fairly objectively describes the situation on the market, and is also able to show a change in trend earlier. It would be convenient to have it in your toolbox.

**Comment by nardew** [comment]
The indicator looks interesting, I may look into it, though I cannot promise when exactly. 

https://www.tradingpedia.com/forex-trading-indicators/schaff-trend-cycle

**Comment by nardew** [comment]
@PieceOfGood the indicator has been released in v1.10.0.

**Comment by PieceOfGood** [comment]
Thanks a lot!
But please tell me how to achieve a similar graph:
![image](https://github.com/nardew/talipp/assets/31653906/0d762f54-c632-4328-9d04-8bc28a794d16)
This graph is obtained as follows:
```python
stc = STC(
    23,
    50,
    10,
    3,
    input_values=close_values
)
```

**Comment by nardew** [comment]
I am not sure what exactly you mean. You want to get a graph like in trading view including zones and colors? Talipp is not a plotting library, it just produces a list of indicator values. To plot things you will need to pass those values to some plotting lib.

**Comment by PieceOfGood** [comment]
No, of course that's not what I mean.
Just by using other `talipp` indicators I was getting almost identical values displayed on the TradingView charts. Confidence that the tool meets expectations eliminates the need to build an additional visualization layer, since this representation is already there and when describing the algorithm, you can be sure that internally its tools are based on the same picture on which the assumptions are based.

If you describe the algorithm based on what the TradingView charts suggest, and the tool generates different values, then the result may be “unexpected”. Therefore, using the `talipp` tools of the same name to describe the algorithm and TradingView to define it, I rely on their identity not only in their name, but also in behavior. It's normal that when you put a sock on your foot, you expect it to be a sock and not a boot, even though they have a similar shape and both are applied to the same place for a very similar purpose.

I'm just asking you, as a direct developer, how to make changes with the least overhead in order to get the expected picture. You understand better than me how your invention works. It seems quite logical to turn to you for competent help.

**Comment by nardew** [comment]
I used standard implementation for STC which internally uses Stoch indicator based on simple moving average. Looking into TradingView's implementation they use exponential moving average inside Stoch. That should explain the differences.

Standard implementation of Stoch is based on the SMA, not EMA, hence I used it in the library.

At the moment it is not possible to change moving average type  but I am planning to add it into version `2.x` of the library. It is currently in progress, you can check its progress in [this PR](https://github.com/nardew/talipp/pull/96). When the functionality is there, I will let you know.

**Comment by PieceOfGood** [comment]
Thank you!
My deepest bow.
