### ISSUE TITLE
How to change D-argument for Stoch-indicator?

### ISSUE THREAD

**Issue by PieceOfGood** [nardew/talipp#82]
By default for `talipp.indicators.Stoch()` it equal 1, but I want to change him for minimize noize.
Tradingview allows you to do this:
![image](https://github.com/nardew/talipp/assets/31653906/cd8d86ce-efe6-49d0-942b-b199e463a71e)
Could you show how to make this change?

**Comment by nardew** [comment]
Stoch is implemented as described [on this page](https://school.stockcharts.com/doku.php?id=technical_indicators:stochastic_oscillator_fast_slow_and_full). `D` is basically smoothed `K`. Smoothing of `D` can be configured by `smoothing_period` parameter.

**Comment by PieceOfGood** [comment]
Yes, he with excellent accuracy accuracy to the values that I see on the chart for the Stoch indicator on tradingview. Its "period" argument corresponds to the setting in the "K Length" field, and the "smoothing_period" argument corresponds to the "D Smooth" field, but does not allow you to change the value that is available in the "K Smooth" field(in the previous picture interface ByBit, this was field "D"), as in the following picture:
![image](https://github.com/nardew/talipp/assets/31653906/6a2a6066-c361-4d85-86db-021996da1f2c)

However changing this value leads to change in the number of signal intersections. It would be useful to have this setting in your implementation as well.
![image](https://github.com/nardew/talipp/assets/31653906/72a887af-9be5-4e10-b80f-8ae8807d2c05)

**Comment by nardew** [comment]
You are right that smoothing of K is missing but you can simulate it easily if you plug K values from Stoch into SMA/EMA or other moving average (depending on the smoothing you are after). I will not plan it for the library for the time being, sorry and thanks for understanding.

**Comment by PieceOfGood** [comment]
Thanks.
