### ISSUE TITLE
Can't find unit tests for PivotsHL

### ISSUE THREAD

**Issue by femtotrader** [nardew/talipp#85]
Hi,

I think tests for PivotsHL are missing.
What is your reference implementation for testing?

Kind regards

https://github.com/nardew/talipp/blob/master/talipp/indicators/PivotsHL.py
https://github.com/search?q=repo%3Anardew%2Ftalipp%20PivotsHL&type=code

**Comment by nardew** [comment]
Same as for https://github.com/nardew/talipp/issues/87.

**Comment by nardew** [comment]
PivotsHL indicator has been deprecated in favour of ZigZag indicator. ZigZag indicator can be configured to act as PivotsHL, see [ZigZag documentation](https://nardew.github.io/talipp/latest/reference/talipp/indicators/ZigZag/?h=zigzag#talipp.indicators.ZigZag.ZigZag) for more details.
