### ISSUE TITLE
Inconsistent naming of parameters period_fast/fast_period and period_slow/slow_period in ChainkinOsc

### ISSUE THREAD

**Issue by femtotrader** [nardew/talipp#86]
Hi,

I noticed

https://github.com/nardew/talipp/blob/b6369e8aaf9cac239ca6a44e7d6f182af319d1f1/talipp/indicators/ChaikinOsc.py#L19-L20

period_fast and period_slow is an inconsistent naming.

See
https://github.com/search?q=repo%3Anardew%2Ftalipp%20fast_period&type=code

it should probably be named fast_period and slow_period to be consistent with others indicators.

Kind regards

**Comment by femtotrader** [comment]
same for internal indicators (fast_ema vs ema_fast) and slow

See
https://github.com/search?q=repo%3Anardew%2Ftalipp+fast_ema&type=code
https://github.com/search?q=repo%3Anardew%2Ftalipp+slow_ema&type=code

https://github.com/search?q=repo%3Anardew%2Ftalipp+ema_fast&type=code
https://github.com/search?q=repo%3Anardew%2Ftalipp+ema_slow&type=code

**Comment by nardew** [comment]
Hi @femtotrader , thanks for the feedback. You are right that parameter names are not consistent across all indicators. However, aligning them is a breaking change and no major release is planned at this moment (basically I do not have enough new features to bundle). I will consider for version 2.x.

**Comment by femtotrader** [comment]
Thanks @nardew for #95

**Comment by nardew** [comment]
@femtotrader Glad to help and thanks for the issues you have opened. I am happy to add additional features into the library if there is a proper use case for them (and size of scope). Feel free to open issues in the future if needed. I cannot promise all of them will be implemented but I will try to prioritize the most burning ones.
