### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by nardew** [nardew/talipp#93]
* for each indicator mention the source
* generate API documentation

**Comment by afkjm** [comment]
Would be nice to understand more clearly what "chaining" is. I'm don't quite get it just from the readme.

**Comment by nardew** [comment]
Hi @afkjm , thanks for the feedback. In the meantime, what exactly is not clear from the example? Output of one indicator simply becomes input of another one.

```python
# Indicator chaining
sma1 = SMA(3)
sma2 = SMA(3, input_indicator = sma1)
sma3 = SMA(3, input_indicator = sma2)

print(f"Chain three moving averages:")
sma1.add([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"SMA1: {sma1}") # [0, 0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
print(f"SMA2: {sma2}") # [0, 0, 0, 0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
print(f"SMA3: {sma3}") # [0, 0, 0, 0, 0, 0, 4.0, 5.0, 6.0, 7.0]
```

**Comment by afkjm** [comment]
Thanks, I see now.

**Comment by nardew** [comment]
Delivered in #125
