### ISSUE TITLE
Add value extractor into each indicator

### ISSUE THREAD

**Issue by nardew** [nardew/talipp#94]

**Comment by femtotrader** [comment]
I wonder if it won't complicate things.
What about instead wrapping indicator inside a ValueExtractor object which contains both the indicator and the lambda function to extract value ?
This is probably what I will do in [IncTA.jl](https://github.com/femtotrader/IncTA.jl)
See https://github.com/joshday/OnlineStats.jl/issues/271
Any opinion?

**Comment by nardew** [comment]
Value extractor is already used at plenty places and works as expected. This issue was just about adding it to the remaining indicators. I am quite happy with the current implementation, I do not see big benefit changing. But if other method suits your library better, then why not :)
